/**
 * Tipos de buque para el desplegable de alta (orden de aparición; sin duplicados exactos).
 * Fuente: listado operativo SICEN.
 */
const RAW_SHIP_TYPES = `
Buque de alojamiento (Accommodation Vessel)
Buque tanque Aframax (Aframax Tanker)
Remolcador de manejo de anclas y suministro — AHTS (Anchor Handling Tug Supply)
Buque antipolución (Anti Pollution Vessel)
Buque tanque de asfalto (Asphalt Tanker)
Buque autónomo de carga (Autonomous Cargo Ship)
Buque transportador de barcazas (Barge Carrier)
Buque tanque de bitumen (Bitumen Tanker)
Buque de abastecimiento de combustible / Bunkero (Bunker Vessel)
Buque científico/oceanográfico (Research Vessel / Oceanographic Vessel)
Buque de apoyo a plataformas (Platform Support Vessel)
Buque de pasajeros (Passenger Ship)
Buque de mantenimiento offshore (Offshore Maintenance Vessel)
Buque escuela (Training Ship)
Buque frigorífico pesquero (Fishing Reefer Vessel)
Buque hospital (Hospital Ship)
Buque híbrido eléctrico de carga (Hybrid Electric Cargo Ship)
Buque nodriza pesquero (Fishing Mother Ship)
Buque Ro-Ro — Rodado de carga (Roll-on/Roll-off Vessel)
Buque cablero (Cable Layer)
Buque de reparación de cables (Cable Repair Vessel)
Granelero Capesize (Capesize Bulk Carrier)
Buque transportador de automóviles — PCC (Pure Car Carrier / Transportador Puro de Automóviles)
Ferry catamarán (Catamaran Ferry)
Cementero (Cement Carrier)
Cerquero (Purse Seiner)
Buque quimiquero (Chemical Tanker)
Buque de carga costera (Coastal Cargo Vessel)
Buque transportador de CO2 — Dióxido de Carbono (Carbon Dioxide Carrier)
Portacontenedores (Container Ship)
Buque grúa (Crane Vessel)
Lancha de transporte de tripulación (Crew Boat)
Petrolero de crudo (Crude Oil Tanker)
Crucero (Cruise Ship)
Dragador de corte y succión (Cutter Suction Dredger)
Buque de apoyo a buceo — DSV (Diving Support Vessel / Buque de Soporte de Buceo)
Dragador (Dredger)
Buque perforador (Drillship)
Crucero de expedición (Expedition Cruise Vessel)
Buque factoría (Factory Ship)
Ferry rápido / Embarcación de alta velocidad (Fast Ferry / High Speed Craft)
Portacontenedores alimentador (Feeder Container Ship)
Ferry (Ferry)
Ferry mixto carga-pasajeros Ro-Pax — Rodado y pasajeros (Roll-on/Roll-off Passenger Vessel)
Buque factoría pesquero (Fish Factory Vessel)
Dique flotante (Floating Dock)
Buque flotante de almacenamiento (Floating Storage Vessel)
Unidad flotante de producción, almacenamiento y descarga — FPSO (Floating Production Storage and Offloading / Unidad Flotante de Producción, Almacenamiento y Descarga)
Unidad flotante de almacenamiento y descarga — FSO (Floating Storage and Offloading / Unidad Flotante de Almacenamiento y Descarga)
Barcaza de combustible (Fuel Barge)
Buque ganadero (Livestock Carrier)
Gasero LNG — Gas Natural Licuado (Liquefied Natural Gas Carrier)
Gasero LPG — Gas Licuado de Petróleo (Liquefied Petroleum Gas Carrier)
Granelero (Bulk Carrier)
Granelero Handymax (Handymax Bulk Carrier)
Granelero Handysize (Handysize Bulk Carrier)
Buque para cargas peligrosas (Hazardous Cargo Vessel)
Buque de carga pesada (Heavy Lift Vessel)
Dragador de tolva por succión en marcha (Trailing Suction Hopper Dredger)
Buque transportador de hidrógeno (Hydrogen Carrier)
Ferry hidroala (Hydrofoil Passenger Vessel)
Rompehielos (Icebreaker)
Buque de carga fluvial interior (Inland Cargo Vessel)
Buque de transporte para plataformas autoelevables (Jack-up Transport Vessel)
Buque LASH — Barcazas a bordo (Lighter Aboard Ship / Buque con Barcazas a Bordo)
Buque de desembarco (Landing Craft)
Buque ganadero (Livestock Carrier)
Buque maderero (Timber Carrier)
Mineralero (Ore Carrier)
Buque multipropósito (Multi-purpose Vessel)
Buque transportador de combustible nuclear (Nuclear Fuel Carrier)
Buque OBO — Mineral, granel y petróleo (Ore Bulk Oil Carrier)
Buque de construcción offshore (Offshore Construction Vessel)
Buque de suministro offshore — OSV (Offshore Supply Vessel / Buque de Suministro Offshore)
Granelero Panamax (Panamax Bulk Carrier)
Buque PCC — Transportador puro de automóviles (Pure Car Carrier)
Buque PCTC — Transportador puro de automóviles y camiones (Pure Car and Truck Carrier)
Pesquero de arrastre (Trawler)
Pesquero palangrero (Longliner)
Petrolero / Tanquero (Oil Tanker)
Buque enterrador de tuberías (Pipe Burial Vessel)
Buque tendedor de tuberías (Pipe Layer)
Portacontenedores (Container Ship)
Buque tanque de productos refinados (Product Tanker)
Buque de carga de proyectos especiales (Project Cargo Vessel)
Buque de suministro a plataformas — PSV (Platform Supply Vessel / Buque de Suministro a Plataformas)
Buque quimiquero (Chemical Tanker)
Buque frigorífico — Reefer (Refrigerated Cargo Vessel)
Remolcador (Tugboat)
Remolcador offshore (Offshore Tug)
Buque de investigación científica (Research Expedition Vessel)
Buque fluvio-marítimo (River-Sea Vessel)
Rompehielos (Icebreaker)
Buque de salvamento (Salvage Vessel)
Buque de prospección sísmica (Seismic Survey Vessel)
Buque semisumergible de carga pesada (Semi-submersible Heavy Lift Vessel)
Petrolero lanzadera (Shuttle Tanker)
Buque recolector de lodos (Sludge Vessel)
Buque de vertido de piedras (Stone Dumping Vessel)
Buque de operaciones submarinas (Subsea Operations Vessel)
Barcaza de suministro (Supply Barge)
Buque tanque Suezmax (Suezmax Tanker)
Buque escuela (Training Ship)
Buque de transbordo de carga (Transshipment Vessel)
Pesquero de arrastre (Trawler)
Portacontenedores ultra grande — ULCV (Ultra Large Container Vessel / Buque Portacontenedores Ultra Grande)
Buque utilitario (Utility Vessel)
Buque de eliminación de residuos (Waste Disposal Vessel)
Barcaza de agua (Water Barge)
Buque de estimulación de pozos petroleros (Well Stimulation Vessel)
Buque instalador de turbinas eólicas (Wind Turbine Installation Vessel)
Buque transportador de yates (Yacht Transport Vessel)
`;

function parseShipTypes(raw) {
  const lines = raw
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);
  const seen = new Set();
  const out = [];
  for (const line of lines) {
    if (seen.has(line)) continue;
    seen.add(line);
    out.push(line);
  }
  return out;
}

export const SHIP_TYPE_OPTIONS = parseShipTypes(RAW_SHIP_TYPES);
